version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: bankapp_postgres
    environment:
      POSTGRES_DB: bankapp
      POSTGRES_USER: bankapp_user
      POSTGRES_PASSWORD: bankapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankapp_user -d bankapp"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
