[tools]
air = "1.62.0"
buf = "1.48.0"

[env]
_.file = '.env'

[tasks.lint]
description = "Run linters."
run = "golangci-lint run"

[tasks.run]
description = "Run `go run`"
run = "go run cmd/app/main.go"
